/*
 * Copyright (c) 2007-2013, Marketo, Inc. All rights reserved.
 * Marketo marketing automation web activity tracking script
 * Version: 142 
 */
 var Munchkin={ASSOCIATE_LEAD:"associateLead",CLICK_LINK:"clickLink",VISIT_WEB_PAGE:"visitWebPage",init:function(a,b){if(_MchHlpr.Cookie.enabled()&&!(null==a||0==a.length)){_MchHlpr.discoverClientLibrary();_MchSingle.id=a;var c=document.location;_MchSingle.notifyPrefix=c.protocol+"//"+_MchSingle.id+".mktoresp.com/";_MchHlpr.isDefined(b)&&(_MchHlpr.isDefined(b.customName)&&(_MchSingle.customName=b.customName),_MchHlpr.isDefined(b.notifyPrefix)&&(_MchSingle.notifyPrefix=b.notifyPrefix),_MchHlpr.isDefined(b.wsInfo)&&
(_MchSingle.wsInfo=b.wsInfo),_MchHlpr.isDefined(b.altIds)&&(_MchSingle.altIds=b.altIds),_MchHlpr.isDefined(b.visitorToken)&&(_MchSingle.visitorToken=b.visitorToken),_MchHlpr.isDefined(b.cookieLifeDays)&&(_MchSingle.cookieLifeDays=b.cookieLifeDays),_MchHlpr.isDefined(b.clickTime)&&(_MchSingle.clickTime=b.clickTime),_MchHlpr.isDefined(b.cookieAnon)&&(_MchSingle.cookieAnon=b.cookieAnon),_MchHlpr.isDefined(b.mkt_tok)&&(_MchSingle.override=b.mkt_tok),_MchHlpr.isDefined(b.domainLevel)&&(_MchSingle.domainLevel=
b.domainLevel));var e="",d=window.location.search;if(null!=d&&0<d.length)for(var d=d.substr(1).split("&"),f=0;f<d.length;f++){var g=d[f].split("=");switch(g[0]){case "mkt_tok":_MchSingle.override=_MchHlpr.decodeURIComponentSafe(g[1]);break;case "lpview":e=g[1];break;case "mkt_dbg":_MchSingle.debug=1==g[1]}}if(!("preview"==e&&/\/lpeditor\/preview$/.test(c.pathname))){_MchSingle.capable=!0;try{_MchHlpr.$(document).ready(function(){_MchSingle.initialize()})}catch(h){}}}},munchkinFunction:function(a,
b,c){var e={};null!=c&&(e._mchKy=c);switch(a){case Munchkin.ASSOCIATE_LEAD:for(var d in b)e["_mchAt"+d]=b[d];_MchSingle.createTrackingCookie(!0);_MchSingle.post("webevents/associateLead",e);break;case Munchkin.CLICK_LINK:null!=b.href&&(e._mchHr=e._mchLr=_MchHlpr.decodeURIComponentSafe(b.href));_MchSingle.post("webevents/clickLink",e,{_mchCn:null!=_MchSingle.customName?_MchSingle.customName:""},0);break;case Munchkin.VISIT_WEB_PAGE:null!=b.url&&(e._mchRu=_MchHlpr.decodeURIComponentSafe(b.url)),null!=
b.params&&(e._mchQp=_MchHlpr.decodeURIComponentSafe(b.params.replace(/&/g,"__-__"))),null!=b.name&&(e._mchCn=b.name),_MchSingle.post("webevents/visitWebPage",e,{_mchRe:_MchHlpr.decodeURIComponentSafe(document.location.href)},0)}},createTrackingCookie:function(a){_MchSingle.createTrackingCookie(a)},debug:function(a,b){var c={_mchId:_MchSingle.Cookie.id,_mchTk:_MchSingle.Cookie.token,_mchMsg:_MchSingle.debugSeq++,_mchUa:navigator.userAgent};null!=_MchSingle.override&&(c.mkt_tok=_MchSingle.override);
null!=a&&(c._mchMsg+=" - "+a);if(null!=b){var e=_MchHlpr.$("#"+b);0<e.length&&(c._mchScr=e.html())}c._mchVr=_MchSingle.VERSION;e=_MchSingle.notifyPrefix+"webevents/debug";e+="?_mchNc="+(new Date).getTime()+"&"+_MchHlpr.$.param(c);c=new Image(1,1);c.onload=function(){};c.src=e}};mktoMunchkin=Munchkin.init;mktoMunchkinDebug=Munchkin.debug;mktoMunchkinFunction=Munchkin.munchkinFunction;
var _MchSingle={capable:!1,inited:!1,id:null,altIds:null,cookie:null,customName:null,override:null,wsInfo:null,visitorToken:null,cookieLifeDays:730,clickTime:250,cookieAnon:!0,debug:!1,debugSeq:1,defQ:[],domainLevel:null,VERSION:"142",LINK_SELECTOR:'a[href]:not([href^="#"],[href=],[class~="mchNoDecorate"],[href^="javascript"],[href^="mailto"]),area[href]:not([href^="#"],[href=],[class~="mchNoDecorate"],[href^="javascript"],[href^="mailto"])',initialize:function(){if(this.capable){if(!this.inited){this.inited=
!0;for(var a=this.createTrackingCookie(null!=this.override);0<this.defQ.length;){var b=this.defQ.shift();switch(b[0]){case "createTrackingCookie":a=this.createTrackingCookie(b[1]);break;case "post":this.post(b[1],b[2],_MchHlpr.isDefined(b[3])?b[3]:null,_MchHlpr.isDefined(b[4])?b[4]:null,_MchHlpr.isDefined(b[5])?b[5]:null)}}null!=a&&(a=document.location,this.post("webevents/visitWebPage",{_mchCn:null!=this.customName?this.customName:""},{_mchHa:_MchHlpr.decodeURIComponentSafe(a.hash),_mchRe:_MchHlpr.decodeURIComponentSafe(document.referrer),
_mchQp:_MchHlpr.decodeURIComponentSafe(a.search.substr(1).replace(/&/g,"__-__"))},0))}}else _MchHlpr.updateLpForm("")},createTrackingCookie:function(a){if(this.inited){if(null!=this.cookie)return this.cookie;this.domain=_MchHlpr.getDomain(document.location.hostname,this.domainLevel);var b=new _MchHlpr.Cookie("_mkto_trk");null!=b.id&&b.id!=this.id&&(b.token=null);return _MchHlpr.isDefined(b.id)||this.cookieAnon||a?(b.id=this.id,null==b.token&&(b.token=null!=this.visitorToken&&"VISITOR_MKTTOK_REPLACE"!=
this.visitorToken?this.visitorToken:_MchHlpr.generateToken(this.domain)),b.store(this.cookieLifeDays,"/",this.domain,!1),_MchHlpr.updateLpForm("id:"+b.id+"&token:"+b.token),this.instrumentLinks(),this.cookie=b):null}this.defQ.push(["createTrackingCookie",a])},post:function(a,b,c,e,d){if(this.inited)if(null!=this.cookie){var f=document.location;b._mchId=this.cookie.id;b._mchTk=this.cookie.token;null!=this.override&&(b.mkt_tok=this.override);null!=this.wsInfo&&(b._mchWs=this.wsInfo);b._mchHo=f.hostname;
b._mchPo=f.port;null==b._mchRu&&(b._mchRu=_MchHlpr.decodeURIComponentSafe(f.pathname));b._mchPc=f.protocol;if(null!=c)for(var g in c)b[g]=c[g];b._mchVr=this.VERSION;if(null==b._mchHo||0==b._mchHo.length||"file:"==b._mchPc)this.debug&&alert("Ignoring munchkin post: "+a);else{a+="?_mchNc="+(new Date).getTime();_MchHlpr.doImageGet(this.notifyPrefix,a,b,e,d);for(var h in this.altIds)c=this.altIds[h],b._mchId=c,_MchHlpr.doImageGet(this.notifyPrefix.replace(/\w{3}\-\w{3}\-\w{3}\.mktoresp\.com/i,c+".mktoresp.com"),
a,b,e)}}else this.debug&&alert("Cannot post without cookie");else this.defQ.push(["post",a,b,c,e,d])},findEventTgtLink:function(a){for(;"A"!=a.tagName&&"AREA"!=a.tagName&&null!=a.parentNode;)a=a.parentNode;return"A"==a.tagName||"AREA"==a.tagName?a:null},addEventListenerRepost:function(a,b){return function(){_MchHlpr.isUndefined(b._mchInRepost)&&(b._mchInRepost=!0,a.dispatchEvent(b))}},addEventListenerDelay:function(a){var b=a.target?a.target:a.srcElement;if(a._mchInRepost||"undefined"!==typeof a.button&&
0!==a.button)return!0;var c=_MchSingle.findEventTgtLink(b);if(null==c||!_MchHlpr.$(c).is(_MchSingle.LINK_SELECTOR))return!0;var e=!1,d=_MchHlpr.$(c).data("events"),d=_MchHlpr.isDefined(d)&&_MchHlpr.isDefined(d.click)&&0<d.click.length,f=""==c.target||"_self"==c.target||"_top"==c.target||"_parent"==c.target;!a.ctrlKey&&(!d&&f)&&(e=!0);var g;e&&(g=document.createEvent("MouseEvents"),g.initMouseEvent("click",a.bubbles,a.cancelable,a.view,a.detail,a.screenX,a.screenY,a.clientX,a.clientY,a.ctrlKey,a.altKey,
a.shiftKey,a.metaKey,a.button,a.relatedTarget),g=_MchSingle.addEventListenerRepost(b,g),a.preventDefault(),a.stopPropagation());_MchSingle.post("webevents/clickLink",{_mchCn:null!=_MchSingle.customName?_MchSingle.customName:"",_mchHr:_MchHlpr.decodeURIComponentSafe(c.href)},null,0,g);return e?(setTimeout(g,_MchSingle.clickTime),!1):!0},instrumentLinks:function(){var a=_MchHlpr.$.browser,b=a.version.indexOf("."),c=-1!=b?a.version.substr(0,b):a.version,b=_MchHlpr.isDefined(a.mozilla)&&a.mozilla&&6>
c,a=_MchHlpr.isDefined(a.msie)&&a.msie&&9>c;b||a?_MchHlpr.$(_MchSingle.LINK_SELECTOR).live("mouseup",function(){null!=this.href&&(0<this.href.length&&!/^mailto:/.test(this.href))&&_MchSingle.post("webevents/clickLink",{_mchCn:null!=_MchSingle.customName?_MchSingle.customName:"",_mchHr:_MchHlpr.decodeURIComponentSafe(this.href)},null,100);return!0}):document.addEventListener&&document.addEventListener("click",function(a){return _MchSingle.addEventListenerDelay(a)},!0)}},_MchHlpr={$:null,jQueryPriv:!1,
clientLib:null,clientLibMajorVer:0,clientLibMinorVer:0,clientLibPatchVer:0,clientLibRevisionVer:0,CLIENT_NONE:0,CLIENT_JQUERY:1,discoverClientLibrary:function(){if(null!=this.clientLib)return this.clientLib;if(!this.jQueryPriv)try{return this.parseVersion(jQuery.fn.jquery),this.clientLib=this.CLIENT_JQUERY}catch(a){}return this.clientLib=this.CLIENT_NONE},parseVersion:function(a){if(this.isDefined(a))a=/^([0-9])\.([0-9])\.?([0-9])?\.?([0-9])?$/.exec(a),null!=a&&(this.clientLibMajorVer=a[1],this.clientLibMinorVer=
a[2],this.isDefined(a[3])&&(this.clientLibPatchVer=a[3]),this.isDefined(a[4])&&(this.clientLibRevisionVer=a[4]));else throw"Invalid version";},doImageGet:function(a,b,c,e,d){b=a+b+"&"+this.$.param(c);var f=!1;a=new Image(1,1);a.onload=function(){f=!0;_MchHlpr.isDefined(d)&&d()};a.src=b;if(0<e)for(b=(new Date).getTime();!f&&!((new Date).getTime()-b>e););},loadAsync:function(a,b){var c=document.createElement("script");c.type="text/javascript";c.async=!0;c.src=a;var e=!1,d=function(){!1===e&&(e=!0,b())};
b&&(c.onreadystatechange=function(){("complete"==this.readyState||"loaded"==this.readyState)&&d()},c.onload=d);document.getElementsByTagName("head")[0].appendChild(c)},updateLpForm:function(a){this.$("input[type=hidden][name=_mkt_trk]").attr("value",a)},getDomain:function(a,b){if(null!=b&&b===parseInt(b)){for(var c=a.split(".");c.length>b&&2<c.length;)c.shift();return c.join(".")}c=/([^.]+\.[^.]{3,})$/i.exec(a);if(null!=c)return c[1];c=/([^.]+\.[^.]+\.[^.]{2})$/i.exec(a);return null!=c?c[1]:a},rand:function(a,
b){return b?Math.floor(Math.random()*(b-a+1))+a:Math.floor(Math.random()*(a+1))},generateToken:function(a){return"_mch-"+a+"-"+(new Date).getTime()+"-"+this.rand(1E4,99999)},isUndefined:function(a){return"undefined"==typeof a},isDefined:function(a){return"undefined"!=typeof a&&null!=a},noOp:function(){},decodeURIComponentSafe:function(a){if(null==a)return null;if(0==a.length)return"";try{return decodeURIComponent(a)}catch(b){var c=a.indexOf("?");if(-1!=c)try{return decodeURIComponent(a.substr(0,c))+
a.substr(c)}catch(e){}return String(a)}},Cookie:function(a){this.$name=a;var b=document.cookie;if(""!=b){for(var c=b.split(";"),e=null,b=0;b<c.length;b++){var d=c[b].replace(/^\s+/,"");if(d.substring(0,a.length+1)==a+"="){e=d;break}}if(null!=e){a=e.substring(a.length+1).split("&");for(b=0;b<a.length;b++)a[b]=a[b].split(":");for(b=0;b<a.length;b++)this[a[b][0]]=_MchHlpr.decodeURIComponentSafe(a[b][1])}}}};
_MchHlpr.Cookie.prototype.store=function(a,b,c,e){var d="",f;for(f in this)if(!("$"==f.charAt(0)||"function"==typeof this[f])){""!=d&&(d+="&");var g=encodeURIComponent(this[f]),d=d+(f+":"+g)}d=this.$name+"="+d;0<a&&(f=new Date,f.setTime(f.getTime()+864E5*a),d+="; expires="+f.toGMTString());b&&(d+="; path="+b);c&&-1!=c.indexOf(".")&&(d+="; domain="+c);e&&(d+="; secure");document.cookie=d};
_MchHlpr.Cookie.enabled=function(){if(void 0!=navigator.cookieEnabled)return navigator.cookieEnabled;if(void 0!=this.Cookie.enabled.cache)return this.Cookie.enabled.cache;document.cookie="testcookie=test; max-age=10000";if(-1==document.cookie.indexOf("testcookie=test"))return this.Cookie.enabled.cache=!1;document.cookie="testcookie=test; max-age=0";return this.Cookie.enabled.cache=!0};
(function(){try{if(_MchHlpr.discoverClientLibrary()==_MchHlpr.CLIENT_JQUERY&&(1==_MchHlpr.clientLibMajorVer&&3<=_MchHlpr.clientLibMinorVer||1<_MchHlpr.clientLibMajorVer))_MchHlpr.$=jQuery;else throw"Invalid jQuery version";}catch(a){_MchHlpr.loadAsync(document.location.protocol+"//munchkin.marketo.net/jquery-latest.min.js",function(){_MchHlpr.$=jQuery.noConflict(!0);_MchHlpr.jQueryPriv=!0;_MchHlpr.$(document).ready(function(){_MchSingle.initialize()})})}})();var MunchkinTracker=Munchkin;
